name: Daily GitHub Trending Crawler
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  daily_crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyquery requests

      - name: Run crawler script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python tel-trending-bot.py
